pipeline { 
    agent any  
    
    tools { 
        maven 'Maven'  
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
                failure
                {
                    mail( body: 'Deliver Stage FAILED', subject: 'Build Report Test stage', to: 'vaibhav.kumar@knoldus.com' )
                }
                success
                {
                    mail( body: 'Deliver Stage succeeded', subject: 'Build Report Test stage', to: 'vaibhav.kumar@knoldus.com' )
                }
                
            }
        }
        stage('Deliver') {
            when {
                expression {
                    BRANCH_NAME == 'prod'
                }
            }
            steps {
                sh 'chmod +x ./jenkins/scripts/deliver.sh'
                sh './jenkins/scripts/deliver.sh'
            }
            post {
                failure
                {
                    mail( body: 'Deliver Stage FAILED', subject: 'Build Report Deliver stage', to: 'vaibhav.kumar@knoldus.com' )
                }
                 success
                {
                    mail( body: 'Deliver Stage succeeded', subject: 'Build Report Deliver stage', to: 'vaibhav.kumar@knoldus.com' )
                }
            }
        }
    }
}
